// Generated by gencpp from file supreme/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SUPREME_MESSAGE_ADDTWOINTS_H
#define SUPREME_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <supreme/AddTwoIntsRequest.h>
#include <supreme/AddTwoIntsResponse.h>


namespace supreme
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace supreme


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::supreme::AddTwoInts > {
  static const char* value()
  {
    return "7727609bad06c3920b54439f5d0595ec";
  }

  static const char* value(const ::supreme::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::supreme::AddTwoInts > {
  static const char* value()
  {
    return "supreme/AddTwoInts";
  }

  static const char* value(const ::supreme::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::supreme::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::supreme::AddTwoInts > 
template<>
struct MD5Sum< ::supreme::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::supreme::AddTwoInts >::value();
  }
  static const char* value(const ::supreme::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::supreme::AddTwoIntsRequest> should match 
// service_traits::DataType< ::supreme::AddTwoInts > 
template<>
struct DataType< ::supreme::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::supreme::AddTwoInts >::value();
  }
  static const char* value(const ::supreme::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::supreme::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::supreme::AddTwoInts > 
template<>
struct MD5Sum< ::supreme::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::supreme::AddTwoInts >::value();
  }
  static const char* value(const ::supreme::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::supreme::AddTwoIntsResponse> should match 
// service_traits::DataType< ::supreme::AddTwoInts > 
template<>
struct DataType< ::supreme::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::supreme::AddTwoInts >::value();
  }
  static const char* value(const ::supreme::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUPREME_MESSAGE_ADDTWOINTS_H
