// Generated by gencpp from file supreme/TrialService.msg
// DO NOT EDIT!


#ifndef SUPREME_MESSAGE_TRIALSERVICE_H
#define SUPREME_MESSAGE_TRIALSERVICE_H

#include <ros/service_traits.h>


#include <supreme/TrialServiceRequest.h>
#include <supreme/TrialServiceResponse.h>


namespace supreme
{

struct TrialService
{

typedef TrialServiceRequest Request;
typedef TrialServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrialService
} // namespace supreme


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::supreme::TrialService > {
  static const char* value()
  {
    return "9f8b5f87d09954c41f9cec2b5c553306";
  }

  static const char* value(const ::supreme::TrialService&) { return value(); }
};

template<>
struct DataType< ::supreme::TrialService > {
  static const char* value()
  {
    return "supreme/TrialService";
  }

  static const char* value(const ::supreme::TrialService&) { return value(); }
};


// service_traits::MD5Sum< ::supreme::TrialServiceRequest> should match 
// service_traits::MD5Sum< ::supreme::TrialService > 
template<>
struct MD5Sum< ::supreme::TrialServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::supreme::TrialService >::value();
  }
  static const char* value(const ::supreme::TrialServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::supreme::TrialServiceRequest> should match 
// service_traits::DataType< ::supreme::TrialService > 
template<>
struct DataType< ::supreme::TrialServiceRequest>
{
  static const char* value()
  {
    return DataType< ::supreme::TrialService >::value();
  }
  static const char* value(const ::supreme::TrialServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::supreme::TrialServiceResponse> should match 
// service_traits::MD5Sum< ::supreme::TrialService > 
template<>
struct MD5Sum< ::supreme::TrialServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::supreme::TrialService >::value();
  }
  static const char* value(const ::supreme::TrialServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::supreme::TrialServiceResponse> should match 
// service_traits::DataType< ::supreme::TrialService > 
template<>
struct DataType< ::supreme::TrialServiceResponse>
{
  static const char* value()
  {
    return DataType< ::supreme::TrialService >::value();
  }
  static const char* value(const ::supreme::TrialServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUPREME_MESSAGE_TRIALSERVICE_H
