// Generated by gencpp from file canusb/CAN.msg
// DO NOT EDIT!


#ifndef CANUSB_MESSAGE_CAN_H
#define CANUSB_MESSAGE_CAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace canusb
{
template <class ContainerAllocator>
struct CAN_
{
  typedef CAN_<ContainerAllocator> Type;

  CAN_()
    : timestamp()
    , stdId(0)
    , extId(0)
    , data()  {
    }
  CAN_(const ContainerAllocator& _alloc)
    : timestamp()
    , stdId(0)
    , extId(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint16_t _stdId_type;
  _stdId_type stdId;

   typedef int32_t _extId_type;
  _extId_type extId;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::canusb::CAN_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::canusb::CAN_<ContainerAllocator> const> ConstPtr;

}; // struct CAN_

typedef ::canusb::CAN_<std::allocator<void> > CAN;

typedef boost::shared_ptr< ::canusb::CAN > CANPtr;
typedef boost::shared_ptr< ::canusb::CAN const> CANConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::canusb::CAN_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::canusb::CAN_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace canusb

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'canusb': ['/home/monster/catkin_ws/src/canusb/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::canusb::CAN_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::canusb::CAN_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canusb::CAN_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canusb::CAN_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canusb::CAN_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canusb::CAN_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::canusb::CAN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "538459a17b716b5d40481761364b2a7c";
  }

  static const char* value(const ::canusb::CAN_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x538459a17b716b5dULL;
  static const uint64_t static_value2 = 0x40481761364b2a7cULL;
};

template<class ContainerAllocator>
struct DataType< ::canusb::CAN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "canusb/CAN";
  }

  static const char* value(const ::canusb::CAN_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::canusb::CAN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n\
uint16 stdId\n\
int32 extId\n\
uint8[] data\n\
";
  }

  static const char* value(const ::canusb::CAN_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::canusb::CAN_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.stdId);
      stream.next(m.extId);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CAN_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::canusb::CAN_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::canusb::CAN_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "stdId: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.stdId);
    s << indent << "extId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.extId);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CANUSB_MESSAGE_CAN_H
