(cl:defpackage SupreMe_Vehicle-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "TRIALSERVICE"
   "<TRIALSERVICE-REQUEST>"
   "TRIALSERVICE-REQUEST"
   "<TRIALSERVICE-RESPONSE>"
   "TRIALSERVICE-RESPONSE"
   "YEDEKSRV"
   "<YEDEKSRV-REQUEST>"
   "YEDEKSRV-REQUEST"
   "<YEDEKSRV-RESPONSE>"
   "YEDEKSRV-RESPONSE"
  ))

