// Generated by gencpp from file SupreMe_Vehicle/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SUPREME_VEHICLE_MESSAGE_ADDTWOINTS_H
#define SUPREME_VEHICLE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <SupreMe_Vehicle/AddTwoIntsRequest.h>
#include <SupreMe_Vehicle/AddTwoIntsResponse.h>


namespace SupreMe_Vehicle
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace SupreMe_Vehicle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::SupreMe_Vehicle::AddTwoInts > {
  static const char* value()
  {
    return "7727609bad06c3920b54439f5d0595ec";
  }

  static const char* value(const ::SupreMe_Vehicle::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::SupreMe_Vehicle::AddTwoInts > {
  static const char* value()
  {
    return "SupreMe_Vehicle/AddTwoInts";
  }

  static const char* value(const ::SupreMe_Vehicle::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::SupreMe_Vehicle::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::SupreMe_Vehicle::AddTwoInts > 
template<>
struct MD5Sum< ::SupreMe_Vehicle::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::SupreMe_Vehicle::AddTwoInts >::value();
  }
  static const char* value(const ::SupreMe_Vehicle::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::SupreMe_Vehicle::AddTwoIntsRequest> should match 
// service_traits::DataType< ::SupreMe_Vehicle::AddTwoInts > 
template<>
struct DataType< ::SupreMe_Vehicle::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::SupreMe_Vehicle::AddTwoInts >::value();
  }
  static const char* value(const ::SupreMe_Vehicle::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::SupreMe_Vehicle::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::SupreMe_Vehicle::AddTwoInts > 
template<>
struct MD5Sum< ::SupreMe_Vehicle::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::SupreMe_Vehicle::AddTwoInts >::value();
  }
  static const char* value(const ::SupreMe_Vehicle::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::SupreMe_Vehicle::AddTwoIntsResponse> should match 
// service_traits::DataType< ::SupreMe_Vehicle::AddTwoInts > 
template<>
struct DataType< ::SupreMe_Vehicle::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::SupreMe_Vehicle::AddTwoInts >::value();
  }
  static const char* value(const ::SupreMe_Vehicle::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUPREME_VEHICLE_MESSAGE_ADDTWOINTS_H
