// Generated by gencpp from file SupreMe_Vehicle/msgstring.msg
// DO NOT EDIT!


#ifndef SUPREME_VEHICLE_MESSAGE_MSGSTRING_H
#define SUPREME_VEHICLE_MESSAGE_MSGSTRING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace SupreMe_Vehicle
{
template <class ContainerAllocator>
struct msgstring_
{
  typedef msgstring_<ContainerAllocator> Type;

  msgstring_()
    : msgtext()  {
    }
  msgstring_(const ContainerAllocator& _alloc)
    : msgtext(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msgtext_type;
  _msgtext_type msgtext;





  typedef boost::shared_ptr< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> const> ConstPtr;

}; // struct msgstring_

typedef ::SupreMe_Vehicle::msgstring_<std::allocator<void> > msgstring;

typedef boost::shared_ptr< ::SupreMe_Vehicle::msgstring > msgstringPtr;
typedef boost::shared_ptr< ::SupreMe_Vehicle::msgstring const> msgstringConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::SupreMe_Vehicle::msgstring_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace SupreMe_Vehicle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'SupreMe_Vehicle': ['/home/monster/catkin_ws/src/SupreMe_Vehicle/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf820a8e464d1831c7daa93d2905b133";
  }

  static const char* value(const ::SupreMe_Vehicle::msgstring_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf820a8e464d1831ULL;
  static const uint64_t static_value2 = 0xc7daa93d2905b133ULL;
};

template<class ContainerAllocator>
struct DataType< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SupreMe_Vehicle/msgstring";
  }

  static const char* value(const ::SupreMe_Vehicle::msgstring_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msgtext\n\
";
  }

  static const char* value(const ::SupreMe_Vehicle::msgstring_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msgtext);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgstring_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::SupreMe_Vehicle::msgstring_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::SupreMe_Vehicle::msgstring_<ContainerAllocator>& v)
  {
    s << indent << "msgtext: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msgtext);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPREME_VEHICLE_MESSAGE_MSGSTRING_H
