// Generated by gencpp from file SupreMe_Vehicle/TrialServiceRequest.msg
// DO NOT EDIT!


#ifndef SUPREME_VEHICLE_MESSAGE_TRIALSERVICEREQUEST_H
#define SUPREME_VEHICLE_MESSAGE_TRIALSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace SupreMe_Vehicle
{
template <class ContainerAllocator>
struct TrialServiceRequest_
{
  typedef TrialServiceRequest_<ContainerAllocator> Type;

  TrialServiceRequest_()
    : user()
    , state(0)  {
    }
  TrialServiceRequest_(const ContainerAllocator& _alloc)
    : user(_alloc)
    , state(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _user_type;
  _user_type user;

   typedef int64_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TrialServiceRequest_

typedef ::SupreMe_Vehicle::TrialServiceRequest_<std::allocator<void> > TrialServiceRequest;

typedef boost::shared_ptr< ::SupreMe_Vehicle::TrialServiceRequest > TrialServiceRequestPtr;
typedef boost::shared_ptr< ::SupreMe_Vehicle::TrialServiceRequest const> TrialServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace SupreMe_Vehicle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'SupreMe_Vehicle': ['/home/monster/catkin_ws/src/SupreMe_Vehicle/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1eb6f4e604cf9edcbc12c3770090457";
  }

  static const char* value(const ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1eb6f4e604cf9edULL;
  static const uint64_t static_value2 = 0xcbc12c3770090457ULL;
};

template<class ContainerAllocator>
struct DataType< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SupreMe_Vehicle/TrialServiceRequest";
  }

  static const char* value(const ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string user\n\
int64 state\n\
";
  }

  static const char* value(const ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrialServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::SupreMe_Vehicle::TrialServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "user: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.user);
    s << indent << "state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPREME_VEHICLE_MESSAGE_TRIALSERVICEREQUEST_H
