// Generated by gencpp from file SupreMe_Vehicle/TrialService.msg
// DO NOT EDIT!


#ifndef SUPREME_VEHICLE_MESSAGE_TRIALSERVICE_H
#define SUPREME_VEHICLE_MESSAGE_TRIALSERVICE_H

#include <ros/service_traits.h>


#include <SupreMe_Vehicle/TrialServiceRequest.h>
#include <SupreMe_Vehicle/TrialServiceResponse.h>


namespace SupreMe_Vehicle
{

struct TrialService
{

typedef TrialServiceRequest Request;
typedef TrialServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrialService
} // namespace SupreMe_Vehicle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::SupreMe_Vehicle::TrialService > {
  static const char* value()
  {
    return "9f8b5f87d09954c41f9cec2b5c553306";
  }

  static const char* value(const ::SupreMe_Vehicle::TrialService&) { return value(); }
};

template<>
struct DataType< ::SupreMe_Vehicle::TrialService > {
  static const char* value()
  {
    return "SupreMe_Vehicle/TrialService";
  }

  static const char* value(const ::SupreMe_Vehicle::TrialService&) { return value(); }
};


// service_traits::MD5Sum< ::SupreMe_Vehicle::TrialServiceRequest> should match 
// service_traits::MD5Sum< ::SupreMe_Vehicle::TrialService > 
template<>
struct MD5Sum< ::SupreMe_Vehicle::TrialServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::SupreMe_Vehicle::TrialService >::value();
  }
  static const char* value(const ::SupreMe_Vehicle::TrialServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::SupreMe_Vehicle::TrialServiceRequest> should match 
// service_traits::DataType< ::SupreMe_Vehicle::TrialService > 
template<>
struct DataType< ::SupreMe_Vehicle::TrialServiceRequest>
{
  static const char* value()
  {
    return DataType< ::SupreMe_Vehicle::TrialService >::value();
  }
  static const char* value(const ::SupreMe_Vehicle::TrialServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::SupreMe_Vehicle::TrialServiceResponse> should match 
// service_traits::MD5Sum< ::SupreMe_Vehicle::TrialService > 
template<>
struct MD5Sum< ::SupreMe_Vehicle::TrialServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::SupreMe_Vehicle::TrialService >::value();
  }
  static const char* value(const ::SupreMe_Vehicle::TrialServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::SupreMe_Vehicle::TrialServiceResponse> should match 
// service_traits::DataType< ::SupreMe_Vehicle::TrialService > 
template<>
struct DataType< ::SupreMe_Vehicle::TrialServiceResponse>
{
  static const char* value()
  {
    return DataType< ::SupreMe_Vehicle::TrialService >::value();
  }
  static const char* value(const ::SupreMe_Vehicle::TrialServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUPREME_VEHICLE_MESSAGE_TRIALSERVICE_H
